networks:
  sajitar-backend-network:
    name: sajitar-backend-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  postgres:
    image: postgres:latest
    container_name: sajitar-postgres
    networks:
      sajitar-backend-network:
        ipv4_address: 10.0.0.10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sajitar-pgadmin
    networks:
      sajitar-backend-network:
        ipv4_address: 10.0.0.15
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped

  springboot:
    image: eclipse-temurin:26-jdk
    container_name: sajitar-springboot
    networks:
      sajitar-backend-network:
        ipv4_address: 10.0.0.20
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.0.10:5432/${POSTGRES_DB}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      SPRING_SQL_BEFORE_FRAMEWORK: ${SPRING_SQL_BEFORE_FRAMEWORK}
      SPRING_SQL_AFTER_FRAMEWORK: ${SPRING_SQL_AFTER_FRAMEWORK}
      SAJITAR_DOMAIN_VALIDATION_PROFILE_BIRTHDAY_MIN_AGE_YEARS: ${SAJITAR_DOMAIN_VALIDATION_PROFILE_BIRTHDAY_MIN_AGE_YEARS}
      SAJITAR_DOMAIN_VALIDATION_LIMIT_MAX: ${SAJITAR_DOMAIN_VALIDATION_LIMIT_MAX}
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: >
      sh -c "apt-get update && apt-get install -y git && tail -f /dev/null"
    restart: unless-stopped
